version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo start prebuild and end it
  build:
    commands:
      - echo Running build
  post_build:
    commands:
      - echo build completed successfully
  
  artifacts:
    files:
      - "**/**"
    base-directory: .